### ISSUE TITLE
[Vite 6] /__vite_hmr doesn't match the route of any of your pages

### ISSUE THREAD

**Issue by fortezhuo** [vikejs/vike-node#32]
I have bumped version to latest vite and encouter vite hmr issue, and after create minimal repo and do some scenario testing, seems the issue lie to vike-node 

Prev discussion with Rom : https://github.com/vikejs/vike/issues/2017
Link repo : https://github.com/fortezhuo/vike6

```
14:54:30 vike6 npm run dev                                                                                                      ✗ (main)

> vike6@0.0.1 dev
> vite

  VITE v6.0.3  ready in 228 ms
  ➜  press h + enter to show help
2:54:32 PM [vike][request(1)] HTTP request: /__vite_hmr
2:54:32 PM [vike][request(1)] URL /__vite_hmr doesn't match the route of any of your pages:
┌───────┬──────────────────┬───────────────────┐
│ ROUTE │ TYPE             │ DEFINED BY        │
├───────┼──────────────────┼───────────────────┤
│ /     │ Filesystem Route │ /src/pages/index/ │
└───────┴──────────────────┴───────────────────┘
See https://vike.dev/routing for more information about routing.
2:54:32 PM [vike][request(1)] HTTP response /__vite_hmr 404
2:54:33 PM [vike][request(2)] HTTP request: /
2:54:33 PM [vike][request(2)] HTTP response / 200
^C
14:54:36 vike6                                                                                                                  ✗ (main)
14:57:23 vike6 npm run dev                                                                                                      ✗ (main)

> vike6@0.0.1 dev
> vite

  VITE v6.0.3  ready in 245 ms
  ➜  press h + enter to show help
2:57:33 PM [vike][request(1)] HTTP request: /__vite_hmr
2:57:33 PM [vike][request(1)] URL /__vite_hmr doesn't match the route of any of your pages:
┌───────┬──────────────────┬───────────────────┐
│ ROUTE │ TYPE             │ DEFINED BY        │
├───────┼──────────────────┼───────────────────┤
│ /     │ Filesystem Route │ /src/pages/index/ │
└───────┴──────────────────┴───────────────────┘
See https://vike.dev/routing for more information about routing.
2:57:33 PM [vike][request(1)] HTTP response /__vite_hmr 404
2:57:34 PM [vike][request(2)] HTTP request: /
2:57:34 PM [vike][request(2)] HTTP response / 200
^C
14:57:37 vike6 npm run dev
```

```
15:27:33 vike6 bun dev                                                                                                          ✗ (main)
$ vite
  VITE v6.0.3  ready in 400 ms
  ➜  press h + enter to show help
Express running at http://localhost:3000
3:27:35 PM [vike][request(1)] HTTP request: /__vite_hmr
3:27:35 PM [vike][request(1)] URL /__vite_hmr doesn't match the route of any of your pages:
┌───────┬──────────────────┬───────────────────┐
│ ROUTE │ TYPE             │ DEFINED BY        │
├───────┼──────────────────┼───────────────────┤
│ /     │ Filesystem Route │ /src/pages/index/ │
└───────┴──────────────────┴───────────────────┘
See https://vike.dev/routing for more information about routing.
3:27:35 PM [vike][request(1)] HTTP response /__vite_hmr 404
3:27:36 PM [vike][request(2)] HTTP request: /
3:27:36 PM [vike][request(2)] HTTP response / 200
^C%
```

**Comment by brillout** [comment]
@magne4000 `vike-node` [has some proxying logic for `/__vite_hmr`](https://github.com/vikejs/vike-node/blob/034fb165cd9aa9d4325ddf419b4ec29ba4cd3a27/packages/vike-node/src/plugin/plugins/devServerPlugin.ts#L12). Maybe it's a regression related to the `universal-middleware` PR? I ain't that familiar with `vike-node` and it's HMR proxying.

**Comment by magne4000** [comment]
Fixed in `0.2.7`.
There was a race condition with the HMR connection handling (could also have happened with `0.1.x` and Vite 5)

**Comment by fortezhuo** [comment]
Thanks for quick fixing.

I have tried in my development project, it run smoothly in development, but when I build using vike-node@latest

```
[2024-12-11 18:59:03] INFO: System - Server running
Error: [@brillout/vite-plugin-server-entry@0.5.4][Wrong Usage] As a library author, make sure your library doesn't call importServerProductionEntry() when using `inject: true`
    at importServerProductionEntry (/Users/forte/Workspace/project/node_modules/@brillout/vite-plugin-server-entry/dist/runtime/importServerProductionEntry.js:11:29)
    at loadImportBuild (file:///Users/forte/Workspace/project/node_modules/vike/dist/esm/node/runtime/globalContext/loadImportBuild.js:13:15)
    at initGlobalContext (file:///Users/forte/Workspace/project/node_modules/vike/dist/esm/node/runtime/globalContext.js:165:36)
    at initGlobalContext_renderPage (file:///Users/forte/Workspace/project/node_modules/vike/dist/esm/node/runtime/globalContext.js:105:11)
    at renderPageAndPrepare (file:///Users/forte/Workspace/project/node_modules/vike/dist/esm/node/runtime/renderPage.js:65:15)
    at file:///Users/forte/Workspace/project/node_modules/vike/dist/esm/node/runtime/renderPage.js:43:81
    at renderPage_wrapper (file:///Users/forte/Workspace/project/node_modules/vike/dist/esm/node/runtime/renderPage.js:25:30)
    at renderPage (file:///Users/forte/Workspace/project/node_modules/vike/dist/esm/node/runtime/renderPage.js:43:41)

````

The errors not occurs while built with 0.1.16

**Comment by brillout** [comment]
> Error: [@brillout/vite-plugin-server-entry@0.5.4][Wrong Usage] As a library author, make sure your library doesn't call importServerProductionEntry() when using `inject: true`


Can you publish a reproduction?

**Comment by fortezhuo** [comment]
I am afraid I can't. Since I don't know which one cause this issue

**Comment by fortezhuo** [comment]
Fortunately, I can still reproduce using previous repo and keep minimal

```
$ vite build
vite v6.0.3 building for production...
✓ 186 modules transformed.
dist/client/_temp_manifest.json                                2.06 kB │ gzip:  0.45 kB
dist/client/assets/static/vike-react-b64a028b.BcWtY8Ol.css     0.06 kB │ gzip:  0.08 kB
dist/client/assets/entries/src_pages_error.BV8bvrJZ.js         2.64 kB │ gzip:  0.71 kB │ map:   0.37 kB
dist/client/assets/entries/src_pages_index.DdJ2fpiD.js         3.68 kB │ gzip:  0.92 kB │ map:   1.63 kB
dist/client/assets/chunks/chunk-DDazF0KO.js                    7.70 kB │ gzip:  2.60 kB │ map:  15.48 kB
dist/client/assets/chunks/chunk-CcfNlH1R.js                   11.14 kB │ gzip:  3.21 kB │ map:  25.58 kB
dist/client/assets/entries/entry-client-routing.D0iVsMt6.js  157.92 kB │ gzip: 34.11 kB │ map: 350.80 kB
dist/client/assets/chunks/chunk-DQp1fYg8.js                  226.16 kB │ gzip: 54.03 kB │ map: 333.35 kB
vite v6.0.3 building SSR bundle for production...
✓ 12 modules transformed.
[plugin @brillout/vite-plugin-server-entry:vike] Sourcemap is likely to be incorrect: a plugin (@brillout/vite-plugin-server-entry:vike) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
dist/server/package.json                 0.02 kB
dist/server/_temp_manifest.json          1.04 kB
dist/server/chunks/chunk-CaJk7cbc.js     0.63 kB │ map: 0.63 kB
dist/server/entries/src_pages_error.mjs  2.31 kB │ map: 0.33 kB
dist/server/entries/src_pages_index.mjs  3.29 kB │ map: 1.55 kB
dist/server/index.mjs                    3.96 kB │ map: 1.42 kB
✓ built in 30ms
✓ built in 995ms
20:49:53 vike6 bun start                                                                                                            (main)
$ node ./dist
[vike][Warning] Running app in production while the environment is set to be a development environment by process.env.NODE_ENV === undefined which is contradictory, see https://vike.dev/NODE_ENV
Error: [@brillout/vite-plugin-server-entry@0.5.4][Wrong Usage] As a library author, make sure your library doesn't call importServerProductionEntry() when using `inject: true`
    at importServerProductionEntry (/Users/forte/Downloads/vike6/node_modules/@brillout/vite-plugin-server-entry/dist/runtime/importServerProductionEntry.js:11:29)
    at loadImportBuild (file:///Users/forte/Downloads/vike6/node_modules/vike/dist/esm/node/runtime/globalContext/loadImportBuild.js:13:15)
    at initGlobalContext (file:///Users/forte/Downloads/vike6/node_modules/vike/dist/esm/node/runtime/globalContext.js:165:36)
    at initGlobalContext_renderPage (file:///Users/forte/Downloads/vike6/node_modules/vike/dist/esm/node/runtime/globalContext.js:105:11)
    at renderPageAndPrepare (file:///Users/forte/Downloads/vike6/node_modules/vike/dist/esm/node/runtime/renderPage.js:65:15)
    at file:///Users/forte/Downloads/vike6/node_modules/vike/dist/esm/node/runtime/renderPage.js:43:81
    at renderPage_wrapper (file:///Users/forte/Downloads/vike6/node_modules/vike/dist/esm/node/runtime/renderPage.js:25:30)
    at renderPage (file:///Users/forte/Downloads/vike6/node_modules/vike/dist/esm/node/runtime/renderPage.js:43:41)
^C%
```

Here link repo : https://github.com/fortezhuo/vike6

**Comment by brillout** [comment]
I cannot reproduce using pnpm and Node.js. It isn't blocking you, right? In that case I'd suggest we have a look at this later. (I'll be able to refactor and simplify a couple of things once I've implemented the Vike CLI.)

**Comment by fortezhuo** [comment]
Hmm.. so weird. I can reproduce using pnpm

Here how to reproduce
- Clone the repo
- ```pnpm install```
- ```pnpm build```
- ```pnpm start```
- open ```localhost:3000```

```
21:06:24 vike6 pnpm start                                                                                                         ✗ (main)
'
> vike6@0.0.1 start /Users/forte/Downloads/vike6
> node ./dist

[vike][Warning] Running app in production while the environment is set to be a development environment by process.env.NODE_ENV === undefined which is contradictory, see https://vike.dev/NODE_ENV
Error: [@brillout/vite-plugin-server-entry@0.5.4][Wrong Usage] As a library author, make sure your library doesn't call importServerProductionEntry() when using `inject: true`
    at importServerProductionEntry (/Users/forte/Downloads/vike6/node_modules/.pnpm/@brillout+vite-plugin-server-entry@0.5.4/node_modules/@brillout/vite-plugin-server-entry/dist/runtime/importServerProductionEntry.js:11:29)
    at loadImportBuild (file:///Users/forte/Downloads/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/globalContext/loadImportBuild.js:13:15)
    at initGlobalContext (file:///Users/forte/Downloads/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/globalContext.js:165:36)
    at initGlobalContext_renderPage (file:///Users/forte/Downloads/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/globalContext.js:105:11)
    at renderPageAndPrepare (file:///Users/forte/Downloads/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/renderPage.js:65:15)
    at file:///Users/forte/Downloads/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/renderPage.js:43:81
    at renderPage_wrapper (file:///Users/forte/Downloads/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/renderPage.js:25:30)
    at renderPage (file:///Users/forte/Downloads/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/renderPage.js:43:41)
^C%
21:06:49 vike6 git add .                                                                                                          ✗ (main)
21:06:57 vike6 git commit -m "Error Vite Plugin Server entry"                                                                     ✗ (main)
[main ef48f77] Error Vite Plugin Server entry
 2 files changed, 2849 insertions(+)
 delete mode 100755 bun.lockb
 create mode 100644 pnpm-lock.yaml
21:07:00 vike6 git push origin main --force                                                                                      +1 (main)
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 32.78 KiB | 32.78 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/fortezhuo/vike6
   4671179..ef48f77  main -> main
21:07:04 vike6```

**Comment by brillout** [comment]
:+1: I can also reproduce following your steps.

It's probably due to your custom tsup build step. Make sure the entry is `dist/server/index.mjs` and not `dist/server/entry.mjs`. I'll be able to improve the error message after I've implemented Vike's CLI.

**Comment by fortezhuo** [comment]
<img width="790" alt="image" src="https://github.com/user-attachments/assets/cc8fb37c-e982-430a-9306-568b6df2c193" />
I checked, the entry is ```dist/server/index.mjs```

**Comment by brillout** [comment]
If it's a blocker for you, then *minimal* reproduction welcome and I'll further dig into it. Otherwise let's dig into this later (after Vike CLI).

**Comment by fortezhuo** [comment]
I already provide minimal repo, right ? The screenshot ia based on the previous repo that you said you can reproduce the error before

**Comment by brillout** [comment]
A repro that doesn't use tsup. (I suspect the culprit to be your tsup setup, but let's see.)

**Comment by fortezhuo** [comment]
Hmm. I don't really get it. I had deployed Hono Vike that built using tsup with same tsup.config.

**Comment by brillout** [comment]
I don't know either, thus a minimal reproduction without tsup would be the best.

**Comment by fortezhuo** [comment]
Noted. 
Step to reproduce 

Here how to reproduce
- ReClone the repo https://github.com/fortezhuo/vike6
- ```pnpm install```
- ```pnpm build```
- ```pnpm preview``` I ditched tsup as requested and using tsx to running ts
- open ```localhost:3000```

```
09:25:48 vike6 pnpm install                                                                                                     ✗ (main)
 WARN  6 deprecated subdependencies found: are-we-there-yet@2.0.0, gauge@3.0.2, glob@7.2.3, inflight@1.0.6, npmlog@5.0.1, rimraf@3.0.2
Packages: +204
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 268, reused 199, downloaded 5, added 204, done
node_modules/.pnpm/esbuild@0.23.1/node_modules/esbuild: Running postinstall script, done in 528ms
node_modules/.pnpm/esbuild@0.24.0/node_modules/esbuild: Running postinstall script, done in 772ms

dependencies:
+ @hono/node-server 1.13.7
+ @vitejs/plugin-react 4.3.4
+ hono 4.6.13
+ react 18.3.1 (19.0.0 is available)
+ react-dom 18.3.1 (19.0.0 is available)
+ vike 0.4.208
+ vike-node 0.2.8
+ vike-react 0.5.10
+ vite 6.0.3

devDependencies:
+ @types/node 22.10.2
+ tsx 4.19.2
+ typescript 5.7.2

Done in 13s
09:26:03 vike6 pnpm preview                                                                                                     ✗ (main)

> vike6@0.0.1 preview /Users/forte/Workspace/HCML/vike6
> NODE_ENV=production tsx ./src/server/index.ts

Error: [@brillout/vite-plugin-server-entry@0.5.4][Wrong Usage] Cannot find server entry. If you use rollupOptions.output.entryFileNames then make sure to not rename the server entry file. Make sure that one of the following exists:
  entry.mjs
  entry.js
  entry.cjs
  entryOthers.mjs
  entryOthers.js
  entryOthers.cjs
    at crawlServerEntry (/Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/@brillout+vite-plugin-server-entry@0.5.4/node_modules/@brillout/vite-plugin-server-entry/dist/runtime/crawlServerEntry.js:64:29)
    at async importServerProductionEntry (/Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/@brillout+vite-plugin-server-entry@0.5.4/node_modules/@brillout/vite-plugin-server-entry/dist/runtime/importServerProductionEntry.js:34:19)
    at async loadImportBuild (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/globalContext/loadImportBuild.js:13:9)
    at async initGlobalContext (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/globalContext.js:165:30)
    at async initGlobalContext_renderPage (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/globalContext.js:105:5)
    at async renderPageAndPrepare (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/renderPage.js:65:9)
    at async renderPage_wrapper (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/renderPage.js:25:24)
    at async renderPage (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/renderPage.js:43:35)
^C ELIFECYCLE  Command failed with exit code 130.
09:27:27 vike6
```

**Comment by fortezhuo** [comment]
Noted. 
Step to reproduce 

Here how to reproduce
- ReClone the repo https://github.com/fortezhuo/vike6
- ```pnpm install```
- ```pnpm build```
- ```pnpm preview``` I ditched tsup as requested and using tsx to running ts
- open ```localhost:3000```

```
09:32:33 vike6 pnpm preview                                                                                                     ✗ (main)

> vike6@0.0.1 preview /Users/forte/Workspace/HCML/vike6
> NODE_ENV=production tsx ./src/server/entry.ts

Error: [@brillout/vite-plugin-server-entry@0.5.4][Wrong Usage] As a library author, make sure your library doesn't call importServerProductionEntry() when using `inject: true`
    at importServerProductionEntry (/Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/@brillout+vite-plugin-server-entry@0.5.4/node_modules/@brillout/vite-plugin-server-entry/dist/runtime/importServerProductionEntry.js:11:29)
    at loadImportBuild (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/globalContext/loadImportBuild.js:13:15)
    at initGlobalContext (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/globalContext.js:165:36)
    at initGlobalContext_renderPage (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/globalContext.js:105:11)
    at renderPageAndPrepare (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/renderPage.js:65:15)
    at file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/renderPage.js:43:81
    at renderPage_wrapper (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/renderPage.js:25:30)
    at renderPage (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/renderPage.js:43:41)
Error: [@brillout/vite-plugin-server-entry@0.5.4][Wrong Usage] As a library author, make sure your library doesn't call importServerProductionEntry() when using `inject: true`
    at importServerProductionEntry (/Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/@brillout+vite-plugin-server-entry@0.5.4/node_modules/@brillout/vite-plugin-server-entry/dist/runtime/importServerProductionEntry.js:11:29)
    at loadImportBuild (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/globalContext/loadImportBuild.js:13:15)
    at initGlobalContext (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/globalContext.js:165:36)
    at initGlobalContext_renderPage (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/globalContext.js:105:11)
    at renderPageAndPrepare (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/renderPage.js:65:15)
    at file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/renderPage.js:43:81
    at renderPage_wrapper (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/renderPage.js:25:30)
    at renderPage (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/renderPage.js:43:41)
^C ELIFECYCLE  Command failed with exit code 130.
```

And I try to add entryFileName in vite config still no luck

```ts
import ssr from "vike/plugin";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import path from "node:path";
import vikeNode from "vike-node/plugin";

export default defineConfig({
  plugins: [
    react({}),
    ssr({}),
    vikeNode({
      entry: {
        index: "src/server/entry.ts",
      },
    }),
  ],
  resolve: {
    dedupe: ["react", "react-dom"],
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  build: {
    sourcemap: true,
    minify: false,
    rollupOptions: {
      output: {
        entryFileNames: "entry.mjs",
        manualChunks: (id) => {},
      },
    },
  },
});
```
> The error not occurs while built with 0.1.16

And as I said before, I assume the culprit still ```vike-node@0.2.x``` 

How to reproduce
After reclone the repo and follow the steps above, please fallback to 0.1.16
- ```pnpm add vike-node@0.1.16```
- ```pnpm build```
- ```pnpm preview```
- open ```localhost:3000``` again

The server can run properly

**Comment by brillout** [comment]
:+1: Let me have a look.

**Comment by fortezhuo** [comment]
I removed pnpm-lock.yaml and redo ```pnpm install``` and run ```pnpm preview``` again.

```
21:12:06 vike6 pnpm preview                                                                                                     ✗ (main)

> vike6@0.0.1 preview /Users/forte/Workspace/HCML/vike6
> NODE_ENV=production tsx ./src/server/entry.ts

Error: [vike@0.4.208][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at loadImportBuild (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/globalContext/loadImportBuild.js:14:9)
    at async initGlobalContext (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/globalContext.js:165:30)
    at async initGlobalContext_renderPage (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/globalContext.js:105:5)
    at async renderPageAndPrepare (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/renderPage.js:65:9)
    at async renderPage_wrapper (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/renderPage.js:25:24)
    at async renderPage (file:///Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_cwy4ebfcnw2h2sduflcpl5efke/node_modules/vike/dist/esm/node/runtime/renderPage.js:43:35)
    at async renderPage (/Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike-node@0.2.8_hono@4.6.13_vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1_jae57eln2rrsgmdlwinhfqdode/node_modules/vike-node/dist/chunk-H3TLS7BK.js:191:23)
    at async <anonymous> (/Users/forte/Workspace/HCML/vike6/node_modules/.pnpm/vike-node@0.2.8_hono@4.6.13_vike@0.4.208_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1_jae57eln2rrsgmdlwinhfqdode/node_modules/vike-node/dist/chunk-H3TLS7BK.js:247:20)

```

**Comment by brillout** [comment]
When I install `vike@0.4.209` I get [this helpful error message](https://github.com/vikejs/vike-node/issues/32#issuecomment-2538756629). Does your pnpm lock also update `@brillout/vite-plugin-ssr` to `0.5.6` (that's where the new error message is implemented)? What are your steps?

To answer the issue itself: follow what the error message says. What you're trying to do doesn't make sense when using `vike-node` since the whole server, including the server entry, is now built.

**Comment by fortezhuo** [comment]
The first time, I used tsup to compile, but you suggested not using tsup for minimal repo.
And I don’t know how to run a TypeScript file without tsx or ts-node.

And I think I almost spend a lot time for this. So please make it quick. Can you explain / elaborate your steps to solve this problem ?

**Comment by brillout** [comment]
Isn’t the new error message clear about what you need to do?

**Comment by fortezhuo** [comment]
I think it is not clear enough. I want to compile into js.

So please, can you elaborate your steps for solving this problem ? And how if I want to use tsup ?

**Comment by brillout** [comment]
To be able to do a PR, I need to first understand what you're trying to achieve. I don't understand what you want: the server is already built to js (thanks to `vike-node`). That's the whole purpose of using `vike-node`: you don't need `ts-node`/`tsx`/`tsup` anymore.

**Comment by brillout** [comment]
I double checked, and indeed I get the new error message:

```bash
~/tmp git clone git@github.com:fortezhuo/vike6
Cloning into 'vike6'...
remote: Enumerating objects: 85, done.
remote: Counting objects: 100% (85/85), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 85 (delta 31), reused 83 (delta 29), pack-reused 0 (from 0)
Receiving objects: 100% (85/85), 120.03 KiB | 1.14 MiB/s, done.
Resolving deltas: 100% (31/31), done.
~/tmp cd vike6/
bun.lockb  package.json  pnpm-lock.yaml  src  tsconfig.json  vite.config.ts
~/tmp/vike6 (main|u=) rm bun.lockb pnpm-lock.yaml 
~/tmp/vike6 (main*|u=) pnpm i
 WARN  6 deprecated subdependencies found: are-we-there-yet@2.0.0, gauge@3.0.2, glob@7.2.3, inflight@1.0.6, npmlog@5.0.1, rimraf@3.0.2
Packages: +204
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 268, reused 203, downloaded 1, added 204, done

dependencies:
+ @hono/node-server 1.13.7
+ @vitejs/plugin-react 4.3.4
+ hono 4.6.13
+ react 18.3.1 (19.0.0 is available)
+ react-dom 18.3.1 (19.0.0 is available)
+ vike 0.4.208
+ vike-node 0.2.8
+ vike-react 0.5.10
+ vite 6.0.3

devDependencies:
+ @types/node 22.10.2
+ tsx 4.19.2
+ typescript 5.7.2

Done in 9.1s
~/tmp/vike6 (main*|u=) pnpm i vike@latest
 WARN  6 deprecated subdependencies found: are-we-there-yet@2.0.0, gauge@3.0.2, glob@7.2.3, inflight@1.0.6, npmlog@5.0.1, rimraf@3.0.2
Packages: +3 -3
+++---
Progress: resolved 268, reused 203, downloaded 1, added 3, done

dependencies:
- vike 0.4.208
+ vike 0.4.209

Done in 2.3s
~/tmp/vike6 (main*|u=) pnpm run build

> vike6@0.0.1 build /home/rom/tmp/vike6
> pnpm build:client


> vike6@0.0.1 build:client /home/rom/tmp/vike6
> vite build

vite v6.0.3 building for production...
✓ 186 modules transformed.
dist/client/_temp_manifest.json                               2.05 kB │ gzip:  0.47 kB
dist/client/assets/static/vike-react-d0049cf3.BcWtY8Ol.css    0.06 kB │ gzip:  0.08 kB
dist/client/entry.mjs                                         2.60 kB │ gzip:  0.69 kB │ map:   0.34 kB
dist/client/entry2.mjs                                        3.64 kB │ gzip:  0.90 kB │ map:   1.61 kB
dist/client/assets/chunks/chunk-CR7PQxe0.js                  11.14 kB │ gzip:  3.21 kB │ map:  27.17 kB
dist/client/entry3.mjs                                      157.73 kB │ gzip: 34.04 kB │ map: 365.73 kB
dist/client/assets/chunks/chunk-tJSoW5rA.js                 233.64 kB │ gzip: 56.39 kB │ map: 350.60 kB
vite v6.0.3 building SSR bundle for production...
✓ 10 modules transformed.
dist/server/package.json         0.02 kB
dist/server/_temp_manifest.json  0.81 kB
dist/server/entry.mjs            1.72 kB │ map: 0.30 kB
dist/server/entry2.mjs           2.70 kB │ map: 1.52 kB
dist/server/entry3.mjs           3.93 kB │ map: 1.57 kB
✓ built in 61ms
✓ built in 2.26s
~/tmp/vike6 (main*|u=) pnpm run preview

> vike6@0.0.1 preview /home/rom/tmp/vike6
> NODE_ENV=production tsx ./src/server/entry.ts

Error: [@brillout/vite-plugin-server-entry@0.5.6][Wrong Usage] Execute the server entry built for production (e.g. $ node dist/server/index.mjs). Don't execute the original server entry (e.g. $ ts-node server/index.ts) and don't run $ vite preview.
    at importServerProductionEntry (/home/rom/tmp/vike6/node_modules/.pnpm/@brillout+vite-plugin-server-entry@0.5.6/node_modules/@brillout/vite-plugin-server-entry/dist/runtime/importServerProductionEntry.js:13:29)
    at loadImportBuild (file:///home/rom/tmp/vike6/node_modules/.pnpm/vike@0.4.209_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_f3xs65hgohhp5y7zswgln4npb4/node_modules/vike/dist/esm/node/runtime/globalContext/loadImportBuild.js:13:15)
    at initGlobalContext (file:///home/rom/tmp/vike6/node_modules/.pnpm/vike@0.4.209_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_f3xs65hgohhp5y7zswgln4npb4/node_modules/vike/dist/esm/node/runtime/globalContext.js:165:36)
    at initGlobalContext_renderPage (file:///home/rom/tmp/vike6/node_modules/.pnpm/vike@0.4.209_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_f3xs65hgohhp5y7zswgln4npb4/node_modules/vike/dist/esm/node/runtime/globalContext.js:105:11)
    at renderPageAndPrepare (file:///home/rom/tmp/vike6/node_modules/.pnpm/vike@0.4.209_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_f3xs65hgohhp5y7zswgln4npb4/node_modules/vike/dist/esm/node/runtime/renderPage.js:65:15)
    at file:///home/rom/tmp/vike6/node_modules/.pnpm/vike@0.4.209_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_f3xs65hgohhp5y7zswgln4npb4/node_modules/vike/dist/esm/node/runtime/renderPage.js:43:81
    at renderPage_wrapper (file:///home/rom/tmp/vike6/node_modules/.pnpm/vike@0.4.209_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_f3xs65hgohhp5y7zswgln4npb4/node_modules/vike/dist/esm/node/runtime/renderPage.js:25:30)
    at renderPage (file:///home/rom/tmp/vike6/node_modules/.pnpm/vike@0.4.209_react-streaming@0.3.44_react-dom@18.3.1_react@18.3.1__react@18.3.1__vite@6.0.3_@_f3xs65hgohhp5y7zswgln4npb4/node_modules/vike/dist/esm/node/runtime/renderPage.js:43:41)
```

**Comment by brillout** [comment]
Then, after removing the rollup config inside your `vite.config.ts`, it works:

![image](https://github.com/user-attachments/assets/0d1e751d-114f-4f29-bd25-d19ff4d5076f)

Make sure to execute `$ node dist/server/index.mjs`, as told by the error message.

**Comment by brillout** [comment]
> I think it is not clear enough.

I actually spent a lot of time on polishing that error message, trying to make it as clear as possible. Let me know if you have ideas on how to improve it.

**Comment by fortezhuo** [comment]
> To be able to do a PR, I need to first understand what you're trying to achieve. I don't understand what you want: the server is already built to js (thanks to `vike-node`). That's the whole purpose of using `vike-node`: you don't need `ts-node`/`tsx`/`tsup` anymore.

Ah. Sorry for misunderstanding the whole error message. But this is more clearer. Maybe for documentation improvement (not need in CLI), just said, we don't need to using ts-node, tsup, tsx, etc. And just execute ```node dist/server/index.mjs```

**Comment by brillout** [comment]
I actually did that 3 days ago https://github.com/vikejs/vike-node/commit/485759dfbfb13a832f89e2741a14976ae1452076.

**Comment by brillout** [comment]
Maybe we can mention this again in the installation steps.

**Comment by fortezhuo** [comment]
> I actually did that 3 days ago [485759d](https://github.com/vikejs/vike-node/commit/485759dfbfb13a832f89e2741a14976ae1452076).

Sorry, I didn’t pay attention to the documentation earlier. This is great! It’s much clearer now for those implementing Vike-node.

> Maybe we can mention this again in the installation steps.
Yes, I think since ```vike-node``` is still in beta, it would be great to follow the latest documentation. on the installation steps. Hopefully, this will help  remind ppl to check the documentation
